#!/bin/bash
# =============================================================================
# Luso8 — Pull secrets from GCP Secret Manager → /opt/luso8/.env
# =============================================================================
# Run on the GCE VM (as root or with sudo).
# The VM's service account has secretmanager.secretAccessor permission.
#
# Called by:
#   - vm-startup.sh (on boot)
#   - luso8-deploy.yml (before every deployment)
#   - reload-config.sh (when admin changes carrier settings)
# =============================================================================
set -euo pipefail

PROJECT="luso8-cloud"
ENV_FILE="/opt/luso8/.env"
PREFIX="luso8-pbx"

echo "[pull-secrets] Fetching configuration from Secret Manager..."

# Helper: fetch a secret value, return empty string on failure
getsecret() {
    gcloud secrets versions access latest \
        --secret="${PREFIX}-$1" \
        --project="$PROJECT" \
        --quiet 2>/dev/null || echo ""
}

# Fetch all secrets
ARI_USERNAME=$(getsecret "ari-username")
ARI_PASSWORD=$(getsecret "ari-password")
SIP_DOMAIN=$(getsecret "sip-domain")
EXTERNAL_IP=$(getsecret "external-ip")
SIP_TRUNK_HOST=$(getsecret "sip-trunk-host")
SIP_TRUNK_USER=$(getsecret "sip-trunk-user")
SIP_TRUNK_PASS=$(getsecret "sip-trunk-pass")
OUTBOUND_CALLER_ID=$(getsecret "outbound-caller-id")
RECORDINGS_BUCKET=$(getsecret "recordings-bucket")

# Validate critical secrets are not empty
ERRORS=0
for VAR_NAME in ARI_USERNAME ARI_PASSWORD SIP_DOMAIN EXTERNAL_IP; do
    VAL="${!VAR_NAME}"
    if [ -z "$VAL" ]; then
        echo "[pull-secrets] ERROR: Secret '${PREFIX}-$(echo $VAR_NAME | tr '[:upper:]' '[:lower:]' | tr '_' '-')' is empty or missing"
        ERRORS=$((ERRORS + 1))
    fi
done

if [ $ERRORS -gt 0 ]; then
    echo "[pull-secrets] $ERRORS critical secret(s) missing. Aborting."
    exit 1
fi

# Write .env atomically (write to temp then move)
TMP_ENV=$(mktemp)
cat > "$TMP_ENV" << EOF
# Generated by pull-secrets.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT EDIT — managed by GCP Secret Manager

# ── ARI ──────────────────────────────────────────────────────────────────
ARI_USERNAME=${ARI_USERNAME}
ARI_PASSWORD=${ARI_PASSWORD}
ARI_PORT=8088
ARI_BIND_ADDR=0.0.0.0
ARI_APP_NAME=voxtra

# ── Network / NAT ────────────────────────────────────────────────────────
SIP_DOMAIN=${SIP_DOMAIN}
EXTERNAL_IP=${EXTERNAL_IP}
LOCAL_NET=10.0.0.0/8

# ── SIP Trunk (Carrier) ──────────────────────────────────────────────────
SIP_TRUNK_HOST=${SIP_TRUNK_HOST:-PLACEHOLDER}
SIP_TRUNK_PORT=5060
SIP_TRUNK_USER=${SIP_TRUNK_USER:-PLACEHOLDER}
SIP_TRUNK_PASS=${SIP_TRUNK_PASS:-PLACEHOLDER}
SIP_TRUNK_REALM=${SIP_TRUNK_HOST:-PLACEHOLDER}

# ── Call Routing ─────────────────────────────────────────────────────────
DEFAULT_CONTEXT=from-carrier
OUTBOUND_CALLER_ID=${OUTBOUND_CALLER_ID:-+000000000000}

# ── RTP Media Ports ──────────────────────────────────────────────────────
RTP_PORT_START=10000
RTP_PORT_END=10100

# ── Logging ──────────────────────────────────────────────────────────────
LOG_LEVEL=notice

# ── Recordings ───────────────────────────────────────────────────────────
RECORDINGS_BUCKET=${RECORDINGS_BUCKET:-luso8-call-recordings}
EOF

chmod 600 "$TMP_ENV"
mv "$TMP_ENV" "$ENV_FILE"
chown root:root "$ENV_FILE"

echo "[pull-secrets] .env written to $ENV_FILE"
echo "[pull-secrets] ARI user     : ${ARI_USERNAME}"
echo "[pull-secrets] SIP domain   : ${SIP_DOMAIN}"
echo "[pull-secrets] External IP  : ${EXTERNAL_IP}"
echo "[pull-secrets] Trunk host   : ${SIP_TRUNK_HOST:-NOT SET}"
echo "[pull-secrets] Caller ID    : ${OUTBOUND_CALLER_ID:-NOT SET}"
